language: generic
sudo: required
services:
        - docker

before_install: 
        - docker build -t kamalikaxilinx/react-test -f ./client/Dockerfile.dev ./client
        

script:
       - docker run -e CI=true kamalikaxilinx/react-test npm test

after_success:
        - docker build -t kamalikaxilinx/multi-client ./client
        - docker build -t kamalikaxilinx/multi-nginx ./nginx
        - docker build -t kamalikaxilinx/multi-server ./server
        - docker build -t kamalikaxilinx/multi-worker ./worker
          
          #Log in to the docker cli
        - echo "$Docker_password" | docker login -u "$Docker_ID" --password-stdin
          #Take those images and push them to docker hub
        - docker push kamalikaxilinx/multi-client
        - docker push kamalikaxilinx/multi-nginx
        - docker push kamalikaxilinx/multi-server
        - docker push kamalikaxilinx/multi-worker


deploy:
        edge: true
        provider: elasticbeanstalk
        region: us-west-1
        app: multi-docker
        env: MultiDocker-env
        bucket_name: elasticbeanstalk-us-west-1-307328585937
        bucket_path: docker-multi
        on:
                branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_key_id: $AWS_SECRET_KEY
